project_id = "rjlzmcwdjwlgnhljbipg"

[functions.accept-family-invitation]
verify_jwt = true

[functions.admin-support]
verify_jwt = true

[functions.admin-team]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.invite-emergency-access]
verify_jwt = true

[functions.invite-family-member]
verify_jwt = true

[functions.rate-limit]
verify_jwt = true

[functions.send-test-mail]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.support-list]
verify_jwt = true

[functions.support-metrics]
verify_jwt = true

[functions.support-submit]
verify_jwt = true

[functions.webauthn]
verify_jwt = true
